### ISSUE TITLE
Full dark theme

### ISSUE THREAD

**Issue by qazip** [conema/monterail-dark#1]
I am aware that you plan to finish the dark theme first, but I thought it good to have an issue for the full dark theme.

Great on you for forking the theme btw, the other repo was pretty much dead.

**Comment by conema** [comment]
I'm closing this, [FullDark version](https://github.com/conema/monterail-fulldark) is ready

Ping @ThexXTURBOXx

**Comment by ThexXTURBOXx** [comment]
I like already! :D Gonna test right away ^^

**Comment by conema** [comment]
Perfect! I'll update soon the theme on the thunderbird market for enable automatic update!
