### ISSUE TITLE
Show dropdown items in Tasks Lightning tab have black color instead of white.

### ISSUE THREAD

**Issue by Rosmaninho** [conema/monterail-dark#11]
![capturar3](https://user-images.githubusercontent.com/42737369/45235542-11b84c80-b2d1-11e8-9141-e27e7525d652.PNG)

The Show dropdown in Tasks are in black instead of White like in the Calendar drop down.

Kudos for the great job!!

**Comment by conema** [comment]
This should be resolved with the last commit in dark/fulldark with the last commit. Thank you for helping me to find these problems!

**Comment by Rosmaninho** [comment]
:D 
Cool!

If you want I could provide you feedback in a couple of other items. But they relate more to minor aesthetic issues.

**Comment by conema** [comment]
Of course!
