### ISSUE TITLE
Way to revert huge padding in message list if in classic layout

### ISSUE THREAD

**Issue by riedel** [conema/monterail-dark#13]
For me it halfs the number of displayable messages if not using vertical layout (like in the original mockup)

I guess that is somehow a wanted behaviour. But it would be great if someone could comment on this bug how to revert this styling of the message list for people using the classical layout. (And just love the colours of the theme.)

**Comment by conema** [comment]
Hi riedel, for remove the padding you should:

1) Close thunderbird and go to
- Linux: `/home/[your linux user]/.thunderbird/[(literally) random letters and numbers].default/extensions`
- Windows: `C:\Users\[your windows user]\AppData\Roaming\Thunderbird\Profiles\[(literally) random letters and numbers].default/extensions`
- MacOS: `/home/[your macos user]/Library/Thunderbird/Profiles/[(literally) random letters and numbers].default/extensions`

2) Open the file "MonterailFullDark@conema.me.xpi" with a zip/rar tool
3) Go to chrome/MonterailOverlay/css/
4) Open the file "root.css" with a file editor (or move the file in the desktop and move it again on the archive after 5.)
5) Go to row 29 and edit "--message-list-row-height" with the hieght that you want
6) Save and start thunderbird

**Comment by riedel** [comment]
Thx! Perfect! For me  ```--message-list-row-height: 1.5rem;``` works nicely (particularly together with the  Theme Font & Size Changer).

**Comment by conema** [comment]
I'm happy to hear that! Remember that you'll need to do the same thing at every theme update.

**Comment by franck-tomek** [comment]
Hello, 
First, thanks for this great theme!
I have a problem trying to modify the css value.
I might not doing the right thing.

What I tried: 
- unzip the xpi with a zip tool and modify the value in root.css. Ok but how to make an xpi again?
- open the xpi with Atom, modify the value in root.css, save. But it seems the value isn't modified, because if I open the file again, it's the default values again.

What am I doing wrong?

**Comment by conema** [comment]
Hi @franck-tomek,

You should do this:

- Unzip the xpi with a zip tool
- Edit root.css, which you can found in the unzipped xpi
- Create a zip archive of the unzipped modified xpi
- Rename the file from name.zip to name.xpi
- Substitute/reinstall the new xpi

**Comment by franck-tomek** [comment]
Well, I just did it several times with different tools, and I can't replace (the file is deleted when opening TB) nor install the new xpi: I have a message it's not compatible with TB 68.9…
Tried on Linux & Mac.

**Comment by conema** [comment]
Open the modified xpi with a zip tool. Do you see these folders?
![immagine](https://user-images.githubusercontent.com/12801153/85925082-740f8200-b896-11ea-9861-3a4a999688de.png)

**Comment by franck-tomek** [comment]
Yes!

**Comment by conema** [comment]
Are the files/folders in the root of the archive?  (The files/folders in the screenshot shouldn't be into a folder)

Did you create the zip without compression?
(The file should be without compression or with deflate)

Are you moving the xpi file in the extensions directory? (It's really strange that you say that the file is being deleted)

If you cannot resolve with this, attach the xpi in a comment.

**Comment by franck-tomek** [comment]
Oh thanks! I was creating the zip from a folder with all files. Did it with just the files and it works, obviously. Sorry for the noise. :-)
