### ISSUE TITLE
Remove the border division between the today Pane and the Toolbar

### ISSUE THREAD

**Issue by Rosmaninho** [conema/monterail-dark#14]
![monterail full dark](https://user-images.githubusercontent.com/42737369/45941528-7ca69a80-bfd6-11e8-8ed3-4fa6ee47c1c2.png)

The Today Pane has a white line as a border between the events toolbar, and the pane itself. Is it possible to remove this border by editing CSS?

**Comment by conema** [comment]
PR #19
