### ISSUE TITLE
Change the color of the column toolbar to the Mail Toolbar color OR to the dark of the Message pane

### ISSUE THREAD

**Issue by Rosmaninho** [conema/monterail-dark#15]
![monterail full dark 2](https://user-images.githubusercontent.com/42737369/45941622-02c2e100-bfd7-11e8-93c4-74135078a59a.png)

As it is right now, it has a different color from both, maybe it would look nicer looking the same color of the Message pane. After all, in Monterail Dark, it has the same color as the Message Pane.

**Comment by conema** [comment]
PR #19
