### ISSUE TITLE
Give the Folder Pane Toolbar the same color as the Mail Toolbar

### ISSUE THREAD

**Issue by Rosmaninho** [conema/monterail-dark#16]
![monterail full dark 3](https://user-images.githubusercontent.com/42737369/45941723-60572d80-bfd7-11e8-803c-537ba2dc3da2.png)

The Folder Pane Toolbar wasn't adjusted. Is it possible to give it the same treatment as the other toolbars?
This would probably have to be applied to Monterail Dark as well...

Hope everything is well with you!! These were the small things I wanted to point out. :)

**Comment by conema** [comment]
PR #19
