### ISSUE TITLE
Change color of the New Task toolbar

### ISSUE THREAD

**Issue by Rosmaninho** [conema/monterail-dark#17]
![monterail full dark 4](https://user-images.githubusercontent.com/42737369/45941834-dfe4fc80-bfd7-11e8-8ac3-a2a006046fe2.png)

In the Calendar tab, the events tab is the same color as the Calendar toolbar. The New Task toolbar should have the same color as well.

It should also be changed in the Monterail Dark theme. :)

**Comment by conema** [comment]
PR #19
