### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by Quanttek** [conema/monterail-dark#22]
As you can see, it is still using the default icons:

![](https://i.imgur.com/7xq2HFG.png)

Edit: the messages also have the same height in the list view as before and not the additional height as in the screenshot

Thunderbird version 60.0 32-bit

**Comment by conema** [comment]
Hi @Quanttek, these icons are the right ones, I'm using the same of Paenglab's [Monterail version](https://addons.thunderbird.net/en-US/thunderbird/addon/monterail/) (that is the original theme by Monterail, with their icon set).

Could you send me a screenshot for the problem with message height?

**Comment by Quanttek** [comment]
@conema Thanks for the quick answer! Having looked at the screenshots in the original blog post and having used spymastermatt's theme, the icons are different ones. The icons above the message are also not changed (reply, reply all, forward, ...). That all may be because of the original add-on but I think it would look better if you would adopt that from spymastermatt

Here's the height problem I meant: ![](https://i.imgur.com/HgfOgg9.png)

**Comment by conema** [comment]
> Here's the height problem I meant: 

This is very strange mhmh
What OS are you using?
Did you remove the userChrome folder with the spymastermatt's theme?

**Comment by Quanttek** [comment]
I’m on Windows 10 and I removed the „chrome“ folder

Von: Emanuele Concas
Gesendet: Dienstag, 2. Oktober 2018 12:43
An: conema/monterail-dark
Cc: Quanttek; Mention
Betreff: Re: [conema/monterail-dark] Icons missing (#22)

Here's the height problem I meant:
This is very strange mhmh
What OS are you using?
Did you remove the userChrome folder with the spymastermatt's theme?

**Comment by conema** [comment]
Did you try to follow the steps listed under "Installation fail/Theme didn't change in Thunderbird 60" in the theme [FAQ](https://github.com/conema/monterail-dark/blob/master/README.md)?

If that doesn't work, could you send me a screenshot of the full thundebird window? Did you download the theme directly from the Thunderbird addon site? Did you have any other addon installed?

I'm sorry for all these questions, I'm with the same OS and TB version, but I cannot replicate this issue.

**Comment by Quanttek** [comment]
@conema I was switching back-and-forth between the monterail theme and your dark theme and I accidentally misascribed the bug to your version. Sorry for the misunderstanding and thanks a lot for your help! Unfortunately, the problem with the icons on top of the message pane still persists.

**Comment by conema** [comment]
No problem, it happens!

> the problem with the icons on top of the message pane still persists.

I'll think about it, but for the moment I'll use the original icons by Monterail.
