### ISSUE TITLE
Date filter in search results not readable

### ISSUE THREAD

**Issue by alexBeuth** [conema/monterail-dark#23]
The date filter in the search results is not readable for me.

![screenshot_20181116_141527](https://user-images.githubusercontent.com/2726077/48623509-20df0900-e9aa-11e8-9957-02907c356341.png)

I am running on Arch Linux with Thunderbird version 60.3.1

It is supposed to look something like the picture below.

![image](https://user-images.githubusercontent.com/2726077/48623628-79aea180-e9aa-11e8-924f-e7437b1cc5ec.png)

**Comment by conema** [comment]
![immagine](https://user-images.githubusercontent.com/12801153/48660342-6231f000-ea60-11e8-9265-07b8a2727667.png)

Fixed with the last commit, thanks for your report!

**Comment by alexBeuth** [comment]
Thank you very much for the fix and your great add-on.
Just as a minor site note: Without the add-on there is a mouse over effect on the bars that is missing in your version.

**Comment by conema** [comment]
I'll mark it down for the next update! Thanks!
