### ISSUE TITLE
Menu above the composition bar isn't themed.

### ISSUE THREAD

**Issue by rickmacgillis** [conema/monterail-dark#27]
**Describe the bug**
The menu above the composition bar isn't themed.

**Expected behavior**
The menu text should be darker.
**Screenshots**
![image](https://user-images.githubusercontent.com/8941225/52455937-a34a1580-2b20-11e9-9121-6640ce6c45b6.png)

**Build information (please complete the following information):**
 - OS: Linux Mint 19.1
 - Version: 60.4.0 (64-bit)

NOTE: This may be related to Issue #9 and happening on multiple OS systems. I tried the patch in the other thread, but it broke it worse. (The whole "Write" screen is no longer themed.)

**Comment by rickmacgillis** [comment]
I deleted my `chrome` directory and reinstalled the theme. Everything is working normally now.

**Comment by conema** [comment]
Thanks for letting us know the solution!
