### ISSUE TITLE
Missing arrow for threaded conversation Mac OS X

### ISSUE THREAD

**Issue by arsounet** [conema/monterail-dark#28]
Hello, 

I found the next issue.

The arrow indicating threaded conversation is missing.

To reproduce it simply install the thunderbird extension and display threads messages.

Obtained rend with Monterail dark :
![image](https://user-images.githubusercontent.com/758451/55318817-ee730b80-5473-11e9-83e7-3e10fe806c27.png)

Expected render like in default template : 
![image](https://user-images.githubusercontent.com/758451/55318691-a48a2580-5473-11e9-9508-556aaa66c4c0.png)

 - OS: Max OS X High Sierra
 - Thunderbird 60.6.1 (64 bits)

I'm not sure this is not the normal awaiting renderer.

**Comment by conema** [comment]
Hi,
I cannot reproduce this on my system (60.6.1/Windows), however, the arrow should be there. 
I'll further investigate in the next days to find a solution.

**Comment by arsounet** [comment]
Hello,

Did you found a solution for this issue? The Paenglab version of Monterail seems to work fine, but your version or Monterail-FullDark and Monterail-Dark fail.
Thank you for your effort.

**Comment by conema** [comment]
Hi @arsounet,
Sadly I didn't found a solution for this issue, I tried to replicate it on Windows and Linux without success and at the moment I don't have a PC with macOS, I should use a virtual machine but I'm pretty busy until the mid of July.
I hope that someone with a mac will take a look at this and solve the bug...

**Comment by micbar84** [comment]
> Hello,
> 
> I found the next issue.
> 
> The arrow indicating threaded conversation is missing.
> 
> To reproduce it simply install the thunderbird extension and display threads messages.
> 
> Obtained rend with Monterail dark :
> ![image](https://user-images.githubusercontent.com/758451/55318817-ee730b80-5473-11e9-83e7-3e10fe806c27.png)
> 
> Expected render like in default template :
> ![image](https://user-images.githubusercontent.com/758451/55318691-a48a2580-5473-11e9-9508-556aaa66c4c0.png)
> 
>     * OS: Max OS X High Sierra
> 
>     * Thunderbird 60.6.1 (64 bits)
> 
> 
> I'm not sure this is not the normal awaiting renderer.

You need to update your Mac to Catalina version (10.15.5 (19F101)) (with TB 68.10): in this way you can see the arrow
