### ISSUE TITLE
Thunderbird Compose Toolbar

### ISSUE THREAD

**Issue by ChuckLabrie** [conema/monterail-dark#29]
**Describe the bug**

**To Reproduce (if applicable)**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

**Build information (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 60.1b]

**Additional context**

**Comment by ChuckLabrie** [comment]
The icons in the compose window (text enhance icons) have a large gap between them. Need to expand the editing window to see all of them. Can the gap be reduced or better yet, can the toolbar wrap or be set to two levels.

Thunderbird 60.7.0
MacOS 10.13.6

![image](https://user-images.githubusercontent.com/51092548/58432395-2a93a880-8080-11e9-8404-e956c38c67da.png)

**Comment by conema** [comment]
Hi Chuck, 
You can change that, you need to edit the chrome/MonterailOverlay/css/root.css file, in row 65 you should find this:
```
toolbar>toolbarbutton {
    margin-right: Ypx !important;
    margin-left: Ypx !important;
}
```
Set Y with the width that you most like, remember to edit the root.css file while TB is closed.

**Comment by ChuckLabrie** [comment]
> Hi Chuck,
> You can change that, you need to edit the chrome/MonterailOverlay/css/root.css file, in row 65 you should find this:
> 
> ```
> toolbar>toolbarbutton {
>     margin-right: Ypx !important;
>     margin-left: Ypx !important;
> }
> ```
> 
> Set Y with the width that you most like, remember to edit the root.css file while TB is closed.

Hi, thanks for your reply but I can't locate the file or path you listed. I am running on a Mac OS 10.13.6 (High Sierra). Do you have another suggestion?

It is the gap between icons of the toolbar that I want to modify. As it is, when composing a new message, I need to drag the editing window significantly to the right in order to see and have access to all icons. Other themes do not behave this way.
![image](https://user-images.githubusercontent.com/51092548/58761370-b179d280-8511-11e9-80c4-96cde00af6a1.png)

**Comment by conema** [comment]
1.  Go to `/home/[your macos user]/Library/Thunderbird/Profiles/[(literally) random letters and numbers].default/extensions`
1. Open `MonterailDark@conema.me.xpi`  with a zip tool

Here you should find the folder that I wrote before.

**Comment by ChuckLabrie** [comment]
Thanks for your patience. Found and modified the file.

**Comment by conema** [comment]
You're welcome!
