### ISSUE TITLE
Doesn't work on my system

### ISSUE THREAD

**Issue by ThexXTURBOXx** [conema/monterail-dark#3]
I am using Windows 10 and Thunderbird 60.0, but the plugin doesn't work on my system. Everything is just the default theme (and yes, it is activated and I have tried restarting and reactivating a lot of times)

**Comment by conema** [comment]
This seems a know bug of Thunderbird 60 [1][2], I'll surely investigate.

PS: I'm going to update the FAQ section of the readme with a workaround, I'll update you.

[1](https://bugzilla.mozilla.org/show_bug.cgi?id=1484393)
[2](http://forums.mozillazine.org/viewtopic.php?f=39&t=3041219)

**Comment by ThexXTURBOXx** [comment]
Okay, thank you very much in advance! :)

**Comment by conema** [comment]
I updated the FAQ with the workaround, tell me if it works!

Could you tell me if you've installed another theme besides this?

**Comment by conema** [comment]
I'm happy to hear that! Full dark version should be coming in the following days

I'll leave this issue opened until TB fixes that

**Comment by ThexXTURBOXx** [comment]
Very cool! Keep up the good work! :)
