### ISSUE TITLE
Changing the colors

### ISSUE THREAD

**Issue by alichakery** [conema/monterail-dark#30]
Hello,

First I wanted to mention that this is not an issue/bug.

As I asked you before, I would like to customize this theme which by far because of several reasons is one of the best Thunderbird themes. 

This is what you mentioned (for those who might have the same question):

> 
> Go where your application data are stored, they usually can be found in:
> - Windows: C:\Users\[your windows user]\AppData\Roaming\Thunderbird\Profiles\[(literally) random letters and numbers].default/
> - Linux: /home/[your linux user]/.thunderbird/[(literally) random letters and numbers].default/
> - MacOS: /home/[your macos user]/Library/Thunderbird/Profiles/[(literally) random letters and numbers].default/
> 
> Go to the "extensions" folder, here there should be a file named "MonterailDark@conema.me.xpi", open it with a zip tool. Go to chrome\MonterailOverlay\css\ and open root.css, in the 21th row you should find "--tree-background-color-selected: #F07746;", change " #F07746" with the color that you want.
> 

Now my question is, will the colors change again if I update this theme ?

And would you please mention if this would be possible to put some options which users would be able to customize the css via the UI of thunderbird ?

Thank you again for the time you have put to make this theme. Thunderbird seems to be abandoned and really needs developers to update the UI to 2019.

Wish you the best.

**Comment by conema** [comment]
Hi @alichakery,
Yes, the colors will change again if the theme will be updated, on the behalf I think that you shouldn't wait for new updates soon, the theme is stable, and importantly, if things didn't changed, complete themes will no more work in the next major release of TB (near July 9th) [1].
For the advice to put options to allow user to change colors via the UI, same as above, if themes will not work in the next major update, I don't think that it will worth the hassle to create a plugin to customize the theme. However, if thing changes and themes will be in someway supported, I'll seriously consider your advice.

I feel the same way as you, TB would need a seriously UI update...

[1][https://www.ghacks.net/2019/05/21/not-all-extensions-will-be-supported-in-thunderbird-68/](https://www.ghacks.net/2019/05/21/not-all-extensions-will-be-supported-in-thunderbird-68/)

**Comment by alichakery** [comment]
Thank you very much.

Its done. Your theme is the only reason which I am staying with Thunderbird. I am using Linux and there are not so may options ... I was about to migrate to Geary but it is really a feature-less client and very limited.

All the best.
