### ISSUE TITLE
Colors do not match the preview

### ISSUE THREAD

**Issue by JPUnD** [conema/monterail-dark#32]
Hi there,

Just a quick bug report, i'm running Manjaro, on kernel 4.19, using thunderbird 60.

Here's a printscreen of what happens when i try to use this theme, and i have tried reinstalling as specified.

![image](https://user-images.githubusercontent.com/41581666/64211042-d1b48700-ce9c-11e9-86f3-e8641afcc89c.png)

**Comment by conema** [comment]
Hi José,
Could you send me a screenshot of the calendar too?
What DE are you using?
TB version is 68.8.0 stable?
Do you have any other plugin installed?

PS: if you plan to use the new version of TB, note that this theme (all full themes in general) will stop working

**Comment by JPUnD** [comment]
WM: i3-gaps 4.17
TB: thunderbird 60.8.0

Not using any other plugin besides grammar check.

Here's a picture of the [calendar](https://i.imgur.com/8i7GFkX.png) which i just activated, don't usually have it on aswell.

**Comment by qba10** [comment]
I have the same issue

**Comment by conema** [comment]
Hi @qba10. this issue should be resolved with the last update, are you using the 2.1 version of the theme with thunderbird >=v68?

**Comment by Vesyrak** [comment]
Hello, I'm having the same issue.
Thunderbird 68.8.0
Theme: Monterail Dark 2 for TB>68
Theme version 2.1 

Added is a screenshot of my calendar
![Screenshot_20200630_110644](https://user-images.githubusercontent.com/7126259/86107759-8d951180-bac2-11ea-90fd-4d262dd51733.png)

Thanks!

**Comment by conema** [comment]
Hi @Vesyrak,
What OS are you using? Do you have the light theme activated?

**Comment by Vesyrak** [comment]
Hey @conema, thanks for the fast response!

Using Kubuntu 20.04 on a Plasma/i3 DE/WM environment.
I did not know of the thunderbird light theme requirement. Changing this did indeed fix those colors, thanks!
However, now the font color of the calendars and the tasks are messed up:
![image](https://user-images.githubusercontent.com/7126259/86133925-42422980-bae9-11ea-81e0-2b447b03a6b1.png)

Thanks in advance

**Comment by conema** [comment]
Should be resolved in the last release.
