### ISSUE TITLE
Enhancement request : configuration for message row spacing

### ISSUE THREAD

**Issue by rnc** [conema/monterail-dark#34]
This is from the discussions in #31 - adding here so it doesn't get forgotten about :-)

It would be useful to have a configuration option so that the height of the message list can match the folder tree height (or can be configurable). The default is 
```
   --message-list-row-height: 40px; 
     --folder-tree-row-height: 25px; 
```
For me, either setting them both to `1.5rem;` or setting `--message-list-row-height: 25px; ` produces a more readable display.

Reference: https://github.com/conema/monterail-dark/issues/31#issuecomment-553060366

**Comment by rnc** [comment]
(for reference this is still (for me) an issue with 3.0 and the relevant file to change in the the xpi is `root.css`

**Comment by conema** [comment]
Hi @rnc, sorry for the wait. I added a settings page to edit these two variable. Could you try it?

To open the settings page, you'll need to go to the "extension" page, click on "Monterail Dark" and open the "options" tab. Remember to restart TB to apply the changes.

New version: [monterail-dark.zip](https://github.com/conema/monterail-dark/files/5361540/monterail-dark.zip)

![immagine](https://user-images.githubusercontent.com/12801153/95685649-6e496c80-0bf9-11eb-8cb6-add7751a9979.png)

**Comment by rnc** [comment]
Just tried it  - perfect - thanks very much!

**Comment by conema** [comment]
The update is officially out in the TB addon site.
