### ISSUE TITLE
[Feature request] Contact photos on message panel list 

### ISSUE THREAD

**Issue by cardozogp** [conema/monterail-dark#36]
I think that humans are more image oriented than text; Maybe for this the montreal mockups show contact photos.

Anyway Ii guess this would be hard to do because load too many photos in a huge inbox could be hardware intensive and some times freeze the application. 

There would be some kind of load photo contacts only for the already  showned messages on the panel list to reduce resource memory usage for example.

**Comment by conema** [comment]
Another problem is that the APIs to retrieve the email profile photos from the email services (gmail, outlook, etc...) are not free. In any case this is a bit out of the scope of the theme, you should try to suggest the same thing to the Thunderbird developers. 
I also saw that there are some plugins which add the profile photos, but only via local files, maybe you could tray them.
