### ISSUE TITLE
Tags colors not working

### ISSUE THREAD

**Issue by maravic** [conema/monterail-dark#37]
Afert update to v68 and install the montereil-dark skin tags colors in main email list window stopped working.

**Comment by conema** [comment]
Hi @maravic,
The version on the master has this issue fixed, the version uploaded on the thunderbird addons page has not. I released the update for the TB addons page, but we need to wait for the completion of the review process.

**Comment by maravic** [comment]
Ok, thx for info, I closed the ticket.

pon., 23 gru 2019, 18:49 użytkownik Emanuele Concas <
notifications@github.com> napisał:

**Comment by conema** [comment]
Just to update you, the update has just got accepted
