### ISSUE TITLE
Changing the Orange Color in Monterail Dark

### ISSUE THREAD

**Issue by alichakery** [conema/monterail-dark#38]
Hello,

I know this is not an issue, but would you please mention that how can I change the Orange color in the new version ?  

I am using 68.2.2

By the way A GREAT THANK YOU for updating this theme for the new TB.

Wish you a merry Christmass and a great new year.

All the best,
Al

**Comment by conema** [comment]
Hi @alichakery,
You need to edit the `skin/root.css` file. From here you can modify all the colors of the theme, the orange should be `#F07746`, so you need just to change all of its occurrences.

Merry Christmas too!

**Comment by alichakery** [comment]
Sorry for opening this up again,

I can not find skin/root.css, would you please mention where can I find it?

I tried the thunderbird profile directory but it was not there.

**Comment by conema** [comment]
No problem, you can find it here:
- Windows: `C:\Users\[your windows user]\AppData\Roaming\Thunderbird\Profiles\[(literally) random letters and numbers].default/extension/MonterailDark2@conema.me.xpi`
- Linux: `/home/[your linux user]/.thunderbird/[(literally) random letters and numbers].default/extension/MonterailDark2@conema.me.xpi`
- MacOS: `/home/[your macos user]/Library/Thunderbird/Profiles/[(literally) random letters and numbers].default/extension/MonterailDark2@conema.me.xpi`

You can treat the .xpi file as a simple .zip archive
