### ISSUE TITLE
not finding the file / therefor not able to adapt font & colors (OS Mojave)

### ISSUE THREAD

**Issue by Ingrid-vr** [conema/monterail-dark#40]
Hi! 
Well done on this theme! Really happy I found it.
However, I would like to make some changes to hightlight color and font size, but I can't seem to find the file you mention anywhere on my computer. I have 0 programming skills, so any idea where I could find it? (did an overall search, combed through library etc.)
Thanks for any help.

**Comment by conema** [comment]
Hi @Ingrid-vr,
Firstly you need to find the .xpi file:
`/home/[your macos user]/Library/Thunderbird/Profiles/[(literally) random letters and numbers].default/extension/MonterailDark2@conema.me.xpi`

Then, exit from Thunderbird, open the .xpi file with a zip tool, like if it was a .zip archive, and edit the file `skin/root.css`. In this file you can change the colors and the font sizes, for example, if you want to change the "select" color of mails in the mail list, you should change row 22, so ` --tree-background-color-selected: #F07746;` and change `#F07746` with the color that you want.  If you want to change the overall font size you can edit `@font-face` (from row 4 to row 9) in this way:
```
@font-face {
    font-family: 'LightSans';
    src: url('fonts/encodesansnarrow-light.woff2') format('woff2'), url('fonts/encodesansnarrow-light.woff') format('woff'), url('fonts/encodesansnarrow-light.ttf') format('truetype'), url('fonts/encodesansnarrow-light.svg#encode_sans_narrowlight') format('svg');
    font-weight: normal;
    font-style: normal;
    font-size: 150%;
}
```
Reopen thunderbird to see your changes.

In general is pretty easy customize the theme, I don't know what's your background, my advice is to give a little look at how CSS works, just to have an insight of the selectors and of the properties.

Remember that your modifications are deleted when the theme is updated, so do a backup of the files which you change.
