### ISSUE TITLE
Tunderbird Beta 73/74

### ISSUE THREAD

**Issue by smrzlina** [conema/monterail-dark#41]
Does not seem to work with Thunderbird Beta 73 or 74.
The xpi could be installed and shows up in the extension Folder, but the theme is not applied.

**Comment by smrzlina** [comment]
One more:
Using the debug option in thunderbird it shows:

`Reading manifest: Warning processing legacy: An unexpected property was found in the WebExtension manifest.`

**Comment by conema** [comment]
Hi @smrzlina,

> Add-on support: As of version 74.0 beta, Thunderbird only supports MailExtensions and MailExtension Experiments. Restartless add-ons and non-restartless legacy add-ons using XUL overlays are no longer supported.
From [TB release note](https://www.thunderbird.net/en-US/thunderbird/74.0beta/releasenotes/)

So it seems that Thunderbird is killing themes for the second time, at the moment MailExtensions didn't offer the same customization of the old "legacy" add-ons.

**Comment by conema** [comment]
#46
