### ISSUE TITLE
Scrollbar colors seems inverted

### ISSUE THREAD

**Issue by frumble** [conema/monterail-dark#42]
Hello, I’m a user of this theme now for years but something isn’t making sense to me at all: The colors of the scrollbar and its 'empty scroll space' are illogically inverted. On most OS’, the scrollbars have a darker color tone than their scroll space. This theme has inverted this paradigm: The scrollbar is lighter than its scroll space. 
![Really confusing](https://user-images.githubusercontent.com/1595877/74937856-346af200-53ed-11ea-84c7-12d4b14359af.png)

**Comment by conema** [comment]
Hi @frumble,
What OS are you using? Do you have enabled the light/dark theme?

**Comment by frumble** [comment]
Hey, this is on Plasma 5.18 on Arch Linux, sorry for the delay! I’ve pinned down the problem to my activating of the integrated dark Thunderbird theme before. If I choose the standard one or the light one, the scrollbars are correct. But as only with the dark one the calendar becomes dark, I have to use this one and then the inverted scrollbars appear.
