### ISSUE TITLE
Color for Tasks on the Today Pane

### ISSUE THREAD

**Issue by BeauFindley** [conema/monterail-dark#43]
I'm running Thunderbird 68.6.0 (32-bit) using Monterail Full Dark v2.1. If you open the Today Pane and switch to a view that includes tasks (such as Events and Tasks), the task part of the pane is only colored dark where there is a task.

Not a huge issue, but I think the intent of the theme is to have the color all the way through the pane. Love the theme though!

![image](https://user-images.githubusercontent.com/47863871/77232725-e292c480-6b70-11ea-9f0b-cc07877f213d.png)

**Comment by conema** [comment]
Hi @BeauFindley,
Thank you for the report. At the moment I can't fix the issue because I'm pretty busy, but if you want a quick fix, while you wait for the theme update, you can open `skin/messenger.css` and add this code:
```
#calendar-task-tree-detail treechildren {
   background: var(--background-color) !important;
}
```

I'll resolve this as soon as possible!

**Comment by conema** [comment]
Resolved in the last commit.
