### ISSUE TITLE
Compatibility with Thunderbird 78.x

### ISSUE THREAD

**Issue by edco100** [conema/monterail-dark#46]
Thunderbird 78 is now the latest available stable release. Unfortunately, this add-on is not compatible.

These are the changes that need to be made: https://developer.thunderbird.net/add-ons/updating/tb78

**Comment by conema** [comment]
I reached out the developers of TB and there are two choices: 
- recreate totaly the theme as a [WebExtensions ](https://developer.mozilla.org/it/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme)(which are pretty limited for now)
- use a [wrapper ](https://github.com/thundernest/addon-developer-support/wiki)(which uses experimental API, that will be removed in the future)

I think that I will take the second choice, as soon as possible.

**Comment by conema** [comment]
I pushed an update version which is compatible with TB 78. Could you test it?

PS: the search result page is without any style, I'm trying to resolve it

**Comment by datumbox** [comment]
@conema I tried installing it from source but did not work. Nothing changed upon installing and loading the addon.

This is the [xpi](https://ufile.io/16k2o03n) I built from source. Could you check if the packaging looks OK to you?

**Comment by conema** [comment]
It seems ok to me, try to install this one to be sure: [monterail-dark-master.zip](https://github.com/conema/monterail-dark/files/5203359/monterail-dark-master.zip). What version of TB are you using? Which OS?

**Comment by datumbox** [comment]
That did not work either. I'm on TB 78.2.1, snap, Ubuntu 20.04.

**Comment by conema** [comment]
Ok, there were some problems with linux/macos, now they should be resolved. Could you try the new version? [monterai-dark.zip](https://github.com/conema/monterail-dark/files/5204030/monterai-dark.zip)

I tested it on Fedora (native and snap), but before too I could see the theme (it was broken, but I could see it). If this doesn't work again, could you also send me a screenshot?

**Comment by datumbox** [comment]
This is strange. I add it and literally nothing happens. I restarted the TB just to be sure but nothing. Let me know when it's released on the store to test again.

**Comment by conema** [comment]
@datumbox the new version is released on the store

**Comment by datumbox** [comment]
@conema It has literally no effect on my app. :( Here is a screenshot: 
![TB](https://i.ibb.co/b7sY3N1/tb.png)

It's worth checking with someone else too in case it's a configuration on my side.

**Comment by conema** [comment]
I tried also with Ubuntu 20 and snap (installing thunderbird with the edge tag), but it works =( 
Could you add also a screenshot of the Add-ons Manager page?
