### ISSUE TITLE
Junk status in list of mails not distinguishable

### ISSUE THREAD

**Issue by hubbty** [conema/monterail-dark#49]
The symbols for junk status in list view are all black no matter which status.

When I disable monterail dark, then these icons have different colors according to junk status.

```
~$ neofetch
       _,met$$$$$gg.          
    ,g$$$$$$$$$$$$$$$P.       ----- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux bullseye/sid x86_64 
 ,$$P'              `$$$.     Host: B450 
',$$P       ,ggs.     `$$b:   Kernel: 5.8.0-3-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 3 hours, 51 mins 
 $$P      d$'     ,    $$P    Packages: xxxx (dpkg), xx (flatpak) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.0.18 
 $$;      Y$b._   _,d$P'      Resolution:  
 Y$$.    `.`"Y$$$$P"'         DE: GNOME 3.38.1 
 `$$b      "-.__              WM: Mutter 
  `Y$$                        WM Theme: Adwaita 
   `Y$$.                      Theme: Greybird [GTK2/3] 
     `$$b.                    Icons: Faenza [GTK2/3]
```

![monterail junk status](https://user-images.githubusercontent.com/59095639/96775140-618dfb00-13e7-11eb-83ae-cec6ef615411.png)

**Comment by conema** [comment]
Hi @hubbty, does the color change if you click the junk icon of a mail?

**Comment by hubbty** [comment]
> Hi @hubbty, does the color change if you click the junk icon of a mail?

No it doesn't when monterail dark is active, without it does.

**Comment by conema** [comment]
I cannot reproduce this issue on the last version (3.1) of the theme on TB 78, but I can reproduce it on TB 68.

From the screenshot, I think that you are using an old version of the theme and/or an old version of Thunderbird. An update of both should resolve this.

**Comment by hubbty** [comment]
Today Thunderbird 78 has arrived from the Bullseye repo. After this update and subsequently that of Monterail Dark to 3.1.0 the bug has gone.
Thank you!

**Comment by conema** [comment]
Perfect! Thank you for the update
