### ISSUE TITLE
Calendar and Tasks no longer visible

### ISSUE THREAD

**Issue by sirmarky** [conema/monterail-dark#50]
**Describe the bug**
Using Thunderbird 78.3.2 after upgrade to Ubuntu 20.10
Using the new updated theme for this version.

**To Reproduce (if applicable)**
Steps to reproduce the behaviour:
1. Go to Thunderbird Calendar or Tasks.  Side views cannot be seen.

**Expected behaviour**
Similar behaviour to older theme version.  Should see the content.

**Screenshots**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/9952028/97474482-0d819a00-1944-11eb-9df7-ae1d395ef2b1.png)
![image](https://user-images.githubusercontent.com/9952028/97474549-1f633d00-1944-11eb-88ae-812f3237331e.png)

**Build information (please complete the following information):**
 - Ubuntu 20.10

**Additional context**
Email view works although the spacing between rows not as wide as before.  All text is, however, visible.

**Comment by conema** [comment]
Hi @sirmarky, could you try to enable the light and dark theme of Thunderbird? Did something change?

**Comment by sorinsfirlogea** [comment]
Hi @conema, let me answer your question: if you select a full dark theme then the problem is corrected, but you also get a black background in places you don't want it. I think you should override the font color for calendar and tasks as you did for mail accounts and folders.

**Comment by conema** [comment]
Hi @sorinsfirlogea, thanks for your reply. I just pushed a fix for this problem, could you double-check?
[monterail-dark.zip](https://github.com/conema/monterail-dark/files/5542716/monterail-dark.zip)

**Comment by sorinsfirlogea** [comment]
Works perfectly. Thanks.

**Comment by sirmarky** [comment]
Apologies for late comment.
Downloaded and tried update listed above.
Mostly looks okay and initial issue is resolved.
Calendar grid at top looks a little odd.  It needs inverting to match theme.

**Comment by conema** [comment]
No problems @sirmarky, the calendar grid looks like the screenshot above?

**Comment by sirmarky** [comment]
Yes, as in the image.Sent from my Galaxy
-------- Original message --------From: Emanuele Concas <notifications@github.com> Date: 15/11/2020  17:37  (GMT+00:00) To: conema/monterail-dark <monterail-dark@noreply.github.com> Cc: sirmarky <sir.marky@googlemail.com>, Mention <mention@noreply.github.com> Subject: Re: [conema/monterail-dark] Calendar and Tasks no longer visible (#50) 
No problems @sirmarky, the calendar grid looks like the screenshot above?
