### ISSUE TITLE
Could I get your input and help for my Zotero dark theme?

### ISSUE THREAD

**Issue by Rosmaninho** [conema/monterail-dark#51]
Hello Conema!

Sorry for reaching out to you like this. I wanted to ask if you could give a look at my Zotero userChrome.css and maybe help me fix some issues with it.
Zotero is based on Firefox so it has a lot in common with Thunderbird.

Here's the link:
https://github.com/Rosmaninho/Zotero-Dark-Theme

**Comment by conema** [comment]
Hi @Rosmaninho, sadly I'm very busy at the moment and I can't help you. My advice is to create some issues in your repo, so me and others can help you one issue at the time when we are free.
