### ISSUE TITLE
[Suggestion] Font Shadows - Change colors to new/unread e-mail

### ISSUE THREAD

**Issue by kionez** [conema/monterail-dark#55]
Hi, I'm using the theme after Thunderbird's 78 update on my linux deskop (mainly Plasma).

I made some improvement in my userChrome.css:

Remove ugly font shadows (maybe is related to my GTK theme, but it was unreadable):
```
* { text-shadow: none !important; }
:root[lwtheme-image]:-moz-lwtheme-brighttext { text-shadow: none !important; }
```

Changed colors to folder with new mail (to easily find in the tree folder):
```
#folderTree > treechildren:-moz-tree-cell-text(isServer-true, biffState-NewMail) { font-weight: bold !important; color: #343434 !important; }
#folderTree > treechildren::-moz-tree-cell-text(folderNameCol, newMessages-true) { font-weight: bold !important; color: #343434 !important; }
#folderTree > treechildren:-moz-tree-cell(isServer-true, biffState-NewMail) { background-color:#19aab3 !important; }
#folderTree > treechildren::-moz-tree-cell(folderNameCol, newMessages-true) { background-color:#19aab3 !important; }
```

Changed colors for new and unread mail in threadview:
```
#threadTree > treechildren::-moz-tree-cell-text(unread) { font-weight:bolder !important; color: #343434 !important; }
#threadTree > treechildren::-moz-tree-cell(new) { background-color:#19aab3 !important; }
#threadTree > treechildren::-moz-tree-cell-text(neww) { -moz-appearance: none !important; color: #343434 !important; font-weight:bolder !important;}
```

Thanks :)

k.

**Comment by rnc** [comment]
How about providing screenshots showing the differences?

**Comment by kionez** [comment]
Sorry, I forgot to attach some screenshots:

Text shadows: [before](https://ibb.co/d5V5FN5) [after](https://ibb.co/BBRQxgn)
Folder colors: [before](https://ibb.co/n3Krhnn) [after](https://ibb.co/tJyZ6KV)
Message colors: [before](https://ibb.co/bHXXhYR) [after](https://ibb.co/NSvHvFm)

PS: I also changed the font-familyI to make it more consistent with other apps.

**Comment by rnc** [comment]
I definitely don't see the first issue - I am using Fedora 33 KDE Spin (up to date) which uses the default GTK Theme of Adwaita. For the latter two changes, while I can see it on my system, in my _personal_ opinion I don't have an issue seeing the new mail, but maybe others, including the maintainer of this project, do have issues with spotting mail. Perhaps they should be options like the message / folder height are? Which I guess you could do as a PR?

**Comment by conema** [comment]
Ciao @kionez,
I also don't see the first issue, but I remember that I read some reviews which were saying that the text was unreadable, thus I will add your fix (thank you!).

For the latter two changes I agree with @rnc, I have no problem to spot the new/unread emails, but it's also true that someone "recently" asked me how to change the background/text color of unread emails. If you have the time (or if someone else want to try) I will accept a PR which adds a setting to change the new/unread email style.
