### ISSUE TITLE
Background highlight of displayed folder not visible when folderpane loses focus

### ISSUE THREAD

**Issue by tsoncrant** [conema/monterail-dark#59]
Beautiful theme for 78.6.0!  A small problem: In the folder pane, the orange highlight of the folder displayed in the message list pane disappears when the folder pane loses focus (unless hovering over the active folder name).  This prevents the user from knowing which folder is open unless he clicks on the folder pane.  This is not the behavior of the native default theme.  Can the highlight be made to stick (even with an alternate color)?

**Comment by conema** [comment]
Hi @tsoncrant, thanks for your report!
I fixed this in the last commit, could you double check it? 

[monterail-dark.zip](https://github.com/conema/monterail-dark/files/5712328/monterail-dark.zip)

**Comment by tsoncrant** [comment]
Works perfectly!  Thanks for the prompt fix.
