### ISSUE TITLE
Change InBox font

### ISSUE THREAD

**Issue by bja-au** [conema/monterail-dark#60]
G'day,
I notice on my linux version of your Addon that you change the InBox font. Is there anywya to stop this happening or have the ability to change to my preference?

Thanks
BJA

**Comment by conema** [comment]
Hi @bja-au,
https://github.com/conema/monterail-dark/blob/41b2c723d20ff60acf9899786cd4dd4e99ab1176/content/skin/root.css#L70-L73

You can change it by editing the "font-family" property. If you want to disable the font change, you can comment the line.

**Comment by bja-au** [comment]
Excellent - thanks
BJA
