### ISSUE TITLE
Folder name color in folder tree with unread emails

### ISSUE THREAD

**Issue by surfatwork** [conema/monterail-dark#62]
Hi,
In the Dark theme, names of folders with unread messages are showing up as dark blue against a dark grey background. Not legible at all. WHat's wrong?
Using Monteral Dark 1.2.5 on Tbird 78.7.0
![image](https://user-images.githubusercontent.com/7880295/106705143-69c71a80-6613-11eb-8172-8b7075ce909d.png)

**Comment by conema** [comment]
Hi @surfatwork,

> Using Monteral Dark 1.2.5
 
The last version is 3.2.1. Did you try to update it?

**Comment by surfatwork** [comment]
Yes. I did. updated to 3.2.1 (my bad, sorry), but the issue remains.
I removed the extension, then reinstalled the latest version. theme changed but same issue
So deleted the xpi file while tbird was running. restarted tbird, and reinstalled. no luck.

**Comment by conema** [comment]
Some question to debug the issue:

- which OS are you using?
- which other addons are you using?
- are you using the default/dark or light Thunderbird theme?
- same as above, but OS theme

**Comment by surfatwork** [comment]
which OS are you using? - Archlinux
which other addons are you using? - Filelink Provider for Dropbox, FIlelink provider for Ownclouc/nextcloud, ImportExportTools NG, Mail Merge, Monterail Dark
are you using the default/dark or light Thunderbird theme? Light, But i also tried setting it to Default and Dark. Issue remains
same as above, but OS theme. I use KDE plasma. It's a light theme in general

**Comment by conema** [comment]
I tried with Fedora (gnome) to reproduce the issue, but with no success. The blue color appears only in folders that have unread emails?

**Comment by surfatwork** [comment]
Yes, only when the folder has unread emails. 
![image](https://user-images.githubusercontent.com/7880295/106835731-deef2a00-66bd-11eb-817a-7a1dfa518f2f.png)

**Comment by surfatwork** [comment]
Update: I tried it with a new ~/.thunderbird folder, and it works fine. So it's some setting in tbird which is causing the issue. Wanted to confirm that it was tbird and not the OS or DE.
![image](https://user-images.githubusercontent.com/7880295/106843126-4eb7e180-66cb-11eb-8db1-55c3c7cf4500.png)

**Comment by surfatwork** [comment]
got it. My mistake (and poor memory)....apologies
Over a year back, I had been experimenting with the older version of Monterail, which needed one to put a userchrome.css inside a chrome folder. That had remained inside the .thunderbird profile folder. The display and colors are fine without that.
Please close this. Apologies for sending you down a rabbit hole

**Comment by conema** [comment]
No problem! Nice to know that this is caused by the older version
