### ISSUE TITLE
Font Colour for Events / Activities in the Today Pane are black

### ISSUE THREAD

**Issue by fence2331** [conema/monterail-dark#65]
The font colour for the events / activities in the Today Pane are black on a dark grey background making them difficult to read. 

Interestingly the Monterail Full Dark has white text on a dark grey background - which is perfect.

**Comment by conema** [comment]
Hi @fence2331,
Could you post a screenshot of the panel?

**Comment by fence2331** [comment]
Here it is - 

![image](https://user-images.githubusercontent.com/80798602/111444170-31604380-875e-11eb-8fb7-75c8a03cb157.png)

**Comment by conema** [comment]
Sorry for the wait, the last commit should fix this issue.
