### ISSUE TITLE
Documentation: Installation from source

### ISSUE THREAD

**Issue by rootwork** [conema/monterail-dark#66]
**Describe the bug**

I'm trying to get the latest version of the theme but it hasn't been updated on the Add-Ons site yet, so I want to install it from the file. The [instructions for doing so](https://github.com/conema/monterail-dark#manual-from-source) don't match the current files in the repo, and I can't figure out what I need to do instead.

**To Reproduce (if applicable)**
1. Read Installation > [Manual (from source)](https://github.com/conema/monterail-dark#manual-from-source)
2. First instruction says "The first step is to download the theme, unzip the contents and re-create a zip only with the content of "monterail-dark" folder." However, there is no such folder. And none of the following options work:

- Creating a zipfile of the entire repo (`monterail-dark-master`)
- Creating a zipfile of the entire repo after removing the `.github` folder
- Creating a zipfile of just the `content` folder in the repo

In all three cases, after renaming the zipfile to .xpi and attempting to install, Thunderbird refuses and says the file is corrupt.

Which part(s) do we need to include when we're creating the zip? (Please update readme in addition to answering here.)

Thanks for this fantastic theme and your continuing work on it!

**Build information (please complete the following information):**
 - OS: Linux Mint/Ubuntu 20.1
 - Version: Thunderbird 78.7.1

**Additional context**

The reason I'm trying to install from source is there's no new release on Add-Ons and I want the fix to #65, so when you get a chance can you cut a new release?

**Comment by conema** [comment]
Hi @rootwork,
The correct way is the first one, but you need to zip the content of the `monterail-dark-master` folder and not of the folder itself

**Comment by rootwork** [comment]
Thanks, that works!
