### ISSUE TITLE
Font too thin.

### ISSUE THREAD

**Issue by sainf** [conema/monterail-dark#71]
Hi.

OS: Linux KDE X11
Version: 91.5

I'm returning to Thunderbird and installed your theme. It's a must, I remember you theme for years...

But the font choice is strange. Is not even 1px in some letters. It's hard to read.
![Screenshot_20220128_202712](https://user-images.githubusercontent.com/1210947/151617776-c805927b-7299-4b06-a283-cc32429693d1.png)

I hack the xpi and replace with NotoSans-Normal and Bold, and the result is much better.
![Screenshot_20220128_202939](https://user-images.githubusercontent.com/1210947/151617936-5ebeb47c-a70c-433f-aab6-b3dc2ba3a92a.png)

Also tested in Windows, it's and is also too thin.
Sorry it's my opinion.

Thanks for this amazing work!

**Comment by conema** [comment]
Hi @sainf,
Maybe in the future I should add a setting to change the font/font size, thanks for the feedback!
