### ISSUE TITLE
v60.0b10 UI Issue on OS X

### ISSUE THREAD

**Issue by benmcnix** [conema/monterail-dark#9]
I really want your theme to work because I love the original by @spymastermatt but I couldn't find out how to get the Quick Filter bar to look normal - It was always too hard to read. In your version, the Quick Filter bar is legible, but the message list is not after clicking the message and rolling the mouse out. I'll give examples via screenshots, but if you need more clarification please let me know. By the way, great work!

I'm running OS X 10.13.6 and Thunderbird 60.0b10. 

Original theme with white on light gray Quick Filter bar:
![Problem with Original Theme](https://user-images.githubusercontent.com/5635267/44665804-6fe55580-a9dc-11e8-978c-2d8f7905e983.png)

Reproduce problem in this theme:
1) Go to folder or Inbox with multiple messages. At first, it appears normal.
![Before clicking](https://user-images.githubusercontent.com/5635267/44665823-7d024480-a9dc-11e8-82fb-0a43c88ff99c.png)

2) Click a message, the row is highlighted, but then you roll your mouse away from the message title row:
![Mouse out](https://user-images.githubusercontent.com/5635267/44665838-82f82580-a9dc-11e8-9174-be8529226a28.png)

3) To view the row again, mouse back over it:
![Mouseover](https://user-images.githubusercontent.com/5635267/44665846-87244300-a9dc-11e8-83f0-9da3770fa0d8.png)

This behavior is when Thunderbird is the foreground app. If I click on the desktop or another window, the message list looks like it does in # 1.

**Comment by conema** [comment]
Hi @benmcnix, thanks for the detailed description of the issue! I'm going to fix this, but, sadly, I haven't MacOS for test the changes, you would do me a favor if you test it for me.

**Comment by conema** [comment]
Here the fix! Try it and let me know if there are any problem.
(You should rename the zip file "fix_monterai_dark_mac.zip" in "fix_monterai_dark_mac.xpi" and install it like a normal theme - more info [here](https://support.mozilla.org/en-US/kb/installing-addon-thunderbird) or in the theme FAQ)

[fix_monterai_dark_mac.zip](https://github.com/conema/monterail-dark/files/2324442/fix_monterai_dark_mac.zip)

**Comment by benmcnix** [comment]
Wow, it worked! 


Here's a screenshot (sorry, doesn't show pointer) that shows proper highlighting without having to mouseover:
![Fixed!](https://user-images.githubusercontent.com/5635267/44672958-bd1ef280-a9ef-11e8-920e-cb7c355624bf.png)


Thanks for the prompt response.  If you need any other mac testing done let me know, I'd be glad to help.

**Comment by conema** [comment]
I think that open an issue if you encounter some other bug in the macos version would be great!
Thanks for your help!
